// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phonerecord.proto

package com.story;

public final class Phonerecord {
  private Phonerecord() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PhoneRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string receNumber = 1;
    /**
     * <code>required string receNumber = 1;</code>
     */
    boolean hasReceNumber();
    /**
     * <code>required string receNumber = 1;</code>
     */
    java.lang.String getReceNumber();
    /**
     * <code>required string receNumber = 1;</code>
     */
    com.google.protobuf.ByteString
        getReceNumberBytes();

    // required string len = 2;
    /**
     * <code>required string len = 2;</code>
     */
    boolean hasLen();
    /**
     * <code>required string len = 2;</code>
     */
    java.lang.String getLen();
    /**
     * <code>required string len = 2;</code>
     */
    com.google.protobuf.ByteString
        getLenBytes();

    // required string date = 3;
    /**
     * <code>required string date = 3;</code>
     */
    boolean hasDate();
    /**
     * <code>required string date = 3;</code>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 3;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    // required string type = 4;
    /**
     * <code>required string type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code com.story.PhoneRecord}
   */
  public static final class PhoneRecord extends
      com.google.protobuf.GeneratedMessage
      implements PhoneRecordOrBuilder {
    // Use PhoneRecord.newBuilder() to construct.
    private PhoneRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PhoneRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PhoneRecord defaultInstance;
    public static PhoneRecord getDefaultInstance() {
      return defaultInstance;
    }

    public PhoneRecord getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              receNumber_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              len_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              date_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              type_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.story.Phonerecord.internal_static_com_story_PhoneRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.story.Phonerecord.internal_static_com_story_PhoneRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.story.Phonerecord.PhoneRecord.class, com.story.Phonerecord.PhoneRecord.Builder.class);
    }

    public static com.google.protobuf.Parser<PhoneRecord> PARSER =
        new com.google.protobuf.AbstractParser<PhoneRecord>() {
      public PhoneRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneRecord(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneRecord> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string receNumber = 1;
    public static final int RECENUMBER_FIELD_NUMBER = 1;
    private java.lang.Object receNumber_;
    /**
     * <code>required string receNumber = 1;</code>
     */
    public boolean hasReceNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string receNumber = 1;</code>
     */
    public java.lang.String getReceNumber() {
      java.lang.Object ref = receNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receNumber = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReceNumberBytes() {
      java.lang.Object ref = receNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string len = 2;
    public static final int LEN_FIELD_NUMBER = 2;
    private java.lang.Object len_;
    /**
     * <code>required string len = 2;</code>
     */
    public boolean hasLen() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string len = 2;</code>
     */
    public java.lang.String getLen() {
      java.lang.Object ref = len_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          len_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string len = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLenBytes() {
      java.lang.Object ref = len_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        len_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string date = 3;
    public static final int DATE_FIELD_NUMBER = 3;
    private java.lang.Object date_;
    /**
     * <code>required string date = 3;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string date = 3;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private java.lang.Object type_;
    /**
     * <code>required string type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      receNumber_ = "";
      len_ = "";
      date_ = "";
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReceNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReceNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReceNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.story.Phonerecord.PhoneRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.story.Phonerecord.PhoneRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.story.Phonerecord.PhoneRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.story.Phonerecord.PhoneRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.story.Phonerecord.PhoneRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.story.Phonerecord.PhoneRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.story.Phonerecord.PhoneRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.story.Phonerecord.PhoneRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.story.Phonerecord.PhoneRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.story.Phonerecord.PhoneRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.story.Phonerecord.PhoneRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.story.PhoneRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.story.Phonerecord.PhoneRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.story.Phonerecord.internal_static_com_story_PhoneRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.story.Phonerecord.internal_static_com_story_PhoneRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.story.Phonerecord.PhoneRecord.class, com.story.Phonerecord.PhoneRecord.Builder.class);
      }

      // Construct using com.story.Phonerecord.PhoneRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        receNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        len_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.story.Phonerecord.internal_static_com_story_PhoneRecord_descriptor;
      }

      public com.story.Phonerecord.PhoneRecord getDefaultInstanceForType() {
        return com.story.Phonerecord.PhoneRecord.getDefaultInstance();
      }

      public com.story.Phonerecord.PhoneRecord build() {
        com.story.Phonerecord.PhoneRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.story.Phonerecord.PhoneRecord buildPartial() {
        com.story.Phonerecord.PhoneRecord result = new com.story.Phonerecord.PhoneRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.receNumber_ = receNumber_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.len_ = len_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.story.Phonerecord.PhoneRecord) {
          return mergeFrom((com.story.Phonerecord.PhoneRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.story.Phonerecord.PhoneRecord other) {
        if (other == com.story.Phonerecord.PhoneRecord.getDefaultInstance()) return this;
        if (other.hasReceNumber()) {
          bitField0_ |= 0x00000001;
          receNumber_ = other.receNumber_;
          onChanged();
        }
        if (other.hasLen()) {
          bitField0_ |= 0x00000002;
          len_ = other.len_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000004;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000008;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReceNumber()) {
          
          return false;
        }
        if (!hasLen()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.story.Phonerecord.PhoneRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.story.Phonerecord.PhoneRecord) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string receNumber = 1;
      private java.lang.Object receNumber_ = "";
      /**
       * <code>required string receNumber = 1;</code>
       */
      public boolean hasReceNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string receNumber = 1;</code>
       */
      public java.lang.String getReceNumber() {
        java.lang.Object ref = receNumber_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          receNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receNumber = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReceNumberBytes() {
        java.lang.Object ref = receNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receNumber = 1;</code>
       */
      public Builder setReceNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        receNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receNumber = 1;</code>
       */
      public Builder clearReceNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        receNumber_ = getDefaultInstance().getReceNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required string receNumber = 1;</code>
       */
      public Builder setReceNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        receNumber_ = value;
        onChanged();
        return this;
      }

      // required string len = 2;
      private java.lang.Object len_ = "";
      /**
       * <code>required string len = 2;</code>
       */
      public boolean hasLen() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string len = 2;</code>
       */
      public java.lang.String getLen() {
        java.lang.Object ref = len_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          len_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string len = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLenBytes() {
        java.lang.Object ref = len_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          len_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string len = 2;</code>
       */
      public Builder setLen(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        len_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string len = 2;</code>
       */
      public Builder clearLen() {
        bitField0_ = (bitField0_ & ~0x00000002);
        len_ = getDefaultInstance().getLen();
        onChanged();
        return this;
      }
      /**
       * <code>required string len = 2;</code>
       */
      public Builder setLenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        len_ = value;
        onChanged();
        return this;
      }

      // required string date = 3;
      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 3;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string date = 3;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 3;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 3;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 3;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        date_ = value;
        onChanged();
        return this;
      }

      // required string type = 4;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.story.PhoneRecord)
    }

    static {
      defaultInstance = new PhoneRecord(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.story.PhoneRecord)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_story_PhoneRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_story_PhoneRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021phonerecord.proto\022\tcom.story\"J\n\013PhoneR" +
      "ecord\022\022\n\nreceNumber\030\001 \002(\t\022\013\n\003len\030\002 \002(\t\022\014" +
      "\n\004date\030\003 \002(\t\022\014\n\004type\030\004 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_story_PhoneRecord_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_story_PhoneRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_story_PhoneRecord_descriptor,
              new java.lang.String[] { "ReceNumber", "Len", "Date", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
